title: Rafael Laya
logo: "/images/logo.jpg?raw=true"
description: > 
  Electrical Engineering student with a focus on Embedded Systems who is looking forward to making devices that connect people together
  <br><br>
  I have posted some projects that I have done on my spare time to gain experience in some technologies. Work and education experience can be found on my LinkedIn profile (Link below) I hope you enjoy!
  <br><br>
  <a href="https://www.linkedin.com/in/rafaellaya/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-148039442-1 

